### PR TITLE
feat(moderators): add moderators cards

### PR DESCRIPTION
**Pull request by BOLT04**
- [x] The UI for the horizontal cards isn't finished on the PR #21. So the moderators code will change in the future.
- [x] Some moderators are missing since I couldn't find their GitHub on the organization. This needs to be added.

## Screenshot in **desktop** screen
imagem

_Note: [First iteration](https://user-images.githubusercontent.com/18630253/91643167-dc124e00-ea28-11ea-84bb-013c1a5cea2c.png)_

## Screenshot in **mobile** screen
imagem

_Note: [First iteration](https://user-images.githubusercontent.com/18630253/91643167-dc124e00-ea28-11ea-84bb-013c1a5cea2c.png)_

Closes: #6

### CODE REVIEW

**Comment by BOLT04** [comment]
@eddiejaoude I've updated the PR and it's ready for review. I changed a bit of the code that is on #21, like:
- not having the star icon
- the website link has a `fa-link` instead of `fa-code-fork`
- wrapping the icon and short word (e.g. GitHub) with a `<a>` tag so it's a link

I still think we can refactor a bit to remove the `style` attibutes and only use Tailwind classes, for example `<i class="fa fa-github-alt pr-1 pt-6 " style="font-size:18px; color:rgb(109, 71, 199); font-style:normal;"></i>`

Also, Arvind I can't tag you with a mention on GitHub, maybe @eddiejaoude needs to invite you to the organization for that feature.

**Comment by eddiejaoude** [comment]
@BOLT04 thank you 👍 .

I think it would be good to make a feature branch for this. I will merge in Arvind PR (and invite to org), then we can merge in your PR to the same branch, then merge it all to `develop`

I am keen to remove the `styles` too

**Comment by BOLT04** [comment]
Off-topic discussion: 
This PR is 300 lines of HTML 😅, could we perhaps create an issue to **investigate the usage of components** on Tailwind CSS to start using it? The goal would be to remove duplication, at least 😃 

What do you guys think?

**Comment by eddiejaoude** [comment]
Yes we need to have reusable components soon 👍

**Pull request merged**
