### PR TITLE
changed the photo to the youtube video on the index.html

### PR DESCRIPTION
**Pull request by Prathamkrishna**
The iframe or any other video link does not allow autoplay unless the video is muted. I felt muting the video would not make any sense, so i let it be. Used the embed link.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you @Prathamkrishna for adding the video 👍 

Could you split the reformatting of the files into another PR, because it is very difficult to see what changes you actually made.

**Comment by Prathamkrishna** [comment]
@eddiejaoude not sure what "split" means here but is it the same as making a new branch?

**Comment by eddiejaoude** [comment]
Sorry for not being clear @Prathamkrishna . This PR contains many line changes, but most of them are reformatting, so it is difficult to see the actual changes.

I suggest creating 2 PRs (2 branches)
1. actual code changes of adding the YouTube video (with no other changes)
2. (optional) reformatting the file - we probably want to add prettier here so everyone formats it the same in the future

**Comment by Prathamkrishna** [comment]
alright @eddiejaoude i'll make a pull request through a new branch, i'll text you on discord right away regarding the reformatting :)

**Comment by eddiejaoude** [comment]
We should try and keep the discussion here so it is not lost in the Discord history, but we can summaries the result here too

**Comment by Prathamkrishna** [comment]
alright sure! Could you help me out with reformatting?

**Comment by eddiejaoude** [comment]
I think it is best to do the [ticket you are tackling first](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/issues/125) because making further improvements.

I think you have 2 options here:
1. remove all the reformatting changes from this PR and only be left with the video being added
2. close this PR and create a new one with only the changes of the video being added

I personally would go with option 2 as it will be easier.

We can discuss the formatting PR and using Prettier afterwards if you still want to make those changes.

**Comment by Prathamkrishna** [comment]
Alright i shall do that right away.

**Comment by eddiejaoude** [comment]
Thanks 👍

**Pull request closed without merging**
