### PR TITLE
Update the README.md

### PR DESCRIPTION
**Pull request by Annysah**
Contents added to the README.md file

### CODE REVIEW

**Review by BOLT04 — COMMENTED** [review]
Thank you for your contribution @Annysah 😃. Could you update the Youtube link to this: https://www.youtube.com/channel/UC5mnBodB73bR88fLXHSfzYA?

**Comment by eddiejaoude** [comment]
Thanks @Annysah and @BOLT04 , this is the short YouTube url http://youtube.com/eddiejaoude

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by Annysah** [comment]
Thanks @eddiejaoude  and @BOLT04 , I have been able to add the changes.

**Comment by eddiejaoude** [comment]
All merged in 🎉

**Comment by Annysah** [comment]
Thank You!!!

**Pull request merged**
