### PR TITLE
Update README with note on multiple tech branches

### PR DESCRIPTION
**Pull request by VictoryWekwa**
This PR fixes issue #97  
Update README with note on multiple tech branches and why they are there.

### CODE REVIEW

**Review by BOLT04 — APPROVED** [review]
LGTM 👍 
I think this is ready to be merged, but @eddiejaoude could you take a look and see if you want something to be added 😃?

**Comment by BOLT04** [comment]
Also @eddiejaoude, the Lighthouse check is failing because it can't post a PR comment. Maybe we have to revisit that `GITHUB_TOKEN`.

**Comment by eddiejaoude** [comment]
Looks good 👍 - I think it adds value already and we can add more to it in another PR if required

**Comment by eddiejaoude** [comment]
Ah the GitHub token is not available in a `fork` for security reasons, it should only run on branches within the upstream repo

**Comment by eddiejaoude** [comment]
@BOLT04 I learnt that there is another event we can use so the token is available for forks. I will give it a try

**Pull request merged**
