### PR TITLE
Adding Discord, GitHub, YouTube badges

### PR DESCRIPTION
**Pull request by vinzvinci**
> I think this looks better? 

badges

### CODE REVIEW

**Comment by Rahma-AlWadhahi** [comment]
I agree with @vinzvinci. The new one does feel better and the colors catches the user attention faster to which link it refers to.

**Comment by Vyvy-vi** [comment]
The new ones look better :+1:

**Review by vinzvinci — COMMENTED** [review]
badges

> I fixed the width of GitHub badge

**Review by BOLT04 — APPROVED** [review]
These look really cool, thank you @vinzvinci 👍

**Comment by eddiejaoude** [comment]
Thanks all 👍

**Pull request merged**
