### PR TITLE
feat: add Svelte with Card component

### PR DESCRIPTION
**Pull request by BOLT04**
This reduces the duplication of the project cards 😃 + we can use Svelte now 🎉 🎉 
**Notes**:
- Moved `img` folder inside of `public` folder
- `tests.yml` was changed to include `build: npm run build` ([commit](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/commit/a0a1c42143106f4f07608bc33cd87b06f0b5821a))
- [degit](https://svelte.dev/blog/the-easiest-way-to-get-started#2_Use_degit) also creates a `scripts/setupTypescript.js`, but I didn't commit that since we are not using Typescript. We can add it later if we so decide, so let me know your opinion in the comments 😃 

The UI didn't change, here is how it looks:
imagem

closes: #68

### CODE REVIEW

**Review by AllanRegush — APPROVED** [review]
Looks Good To Me :+1:

**Comment by eddiejaoude** [comment]
Awesome @BOLT04 thank you 👍 .

Some of my thoughts:

- I think the `QuickStart` in the `README.md` needs updating for the new `npm` commands
- the hot reload didnt work for me locally, I had to rebuild and start the local web server again, even when running `npm run dev` - maybe I missed a step?

**Comment by BOLT04** [comment]
@AllanRegush and @eddiejaoude thank you for your feedback 😃. I forgot to update the README and delete the index.html at the root (that is not necessary now), so I'll make those changes.
About the hot reload @eddiejaoude that is weird. When I run `npm run dev` and make changes I get these logs that it's waiting for changes:
imagem

I'll try to do a clean test of cloning this repository and testing it out.

**Comment by eddiejaoude** [comment]
Thank you for making those updates @BOLT04 . Looks good 👍 

> When I run npm run dev and make changes I get these logs that it's waiting for changes:

The logs run, but the webpage doesn't reload and if I refresh it, I don't see the changes 🤔 

Screenshot 2020-09-26 at 14 26 17

**Review by Karem1986 — COMMENTED** [review]
Hi David!
Nice to see your contributions:)
WHat is Svelter? please send me links/resources so I can provide a deep review of adding Svelte to our project.
Look forward to hearing from you,
Karem

**Comment by Karem1986** [comment]
Eddie, perhaps doing a git pull first and after a refreshing the page helps?

**Comment by eddiejaoude** [comment]
Thanks @Karem1986 👍 - if you get time, if you could try this branch too, make a change and see if the live reload works fine, it might just me that has an issue 😂

**Comment by BOLT04** [comment]
Hi @Karem1986 😃, did you mean Svelte by "Svelter"? If not then I don't know what that is 😅.

Here are a few links that helped me get started and the community has also shared on the Discord channel:
- https://svelte.dev/blog/the-easiest-way-to-get-started
- https://svelte.school/tutorials/introduction-to-actions
- https://sapper.svelte.dev/
- https://elderguide.com/tech/elderjs/
- [Svelte introduction with core maintainer Tan Li Hau livestream](https://www.youtube.com/watch?v=FOuIwyD9ftY  )

**Comment by BOLT04** [comment]
@eddiejaoude I tested it locally again and it seems to work, here is my test: https://recordit.co/jBapeBoiFG.
Can anyone else test this branch or is it just working for me 😅 ?

**Comment by alrifay** [comment]
> Can anyone else test this branch or is it just working for me 😅 ?

@BOLT04  It works fine with me 👌
image

**Comment by AllanRegush** [comment]
@BOLT04 @eddiejaoude `npm run dev` is working for me

**Comment by BOLT04** [comment]
> 
> 
> > Can anyone else test this branch or is it just working for me 😅 ?
> 
> @BOLT04 It works fine for me 👌. but it doesn't work on CodeSpaces, because live reload uses deferent port other than 8080 😁
> image

ahh I see. Well, the default port from Svelte is 5000. I changed it for the cypress tests to work, but when I made that change I thought if we couldn't just receive the port from an env var here: https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/blob/499fdad7bd1247ceb59adef6925809b77b460f60/cypress/support/step_definitions/navigate.js#L3

@alrifay do you think we could change it to a different port and it would work?

**Comment by alrifay** [comment]
> do you think we could change it to a different port and it would work?

@BOLT04 I don't think changing the port will fix it because when the dev server starts on CodeSpases on any port it will be forwarded to port 80 so we can open the site in the browser and it opens fine, the problem is the livereload plugin starts another server that uses different port(random port) and injects itself in JavaScript without using the correct forwarded port.

I don't know if I'm descripting the issue clearly or not but everything works fine on local environment 😁

See issue https://github.com/thgh/rollup-plugin-livereload/issues/20 to understand me  😁

**Comment by eddiejaoude** [comment]
Thanks @AllanRegush and @alrifay for testing, it must just be me 😢 - I will take a closer look. 

I suggest lets get this merged and we can add improvements later on in another PR.

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍

**Comment by eddiejaoude** [comment]
I just realised it wont deploy to GitHub Pages as it is not the `index.html` file anymore in the root. We can get that done in another PR

**Pull request merged**
