### PR TITLE
Cypress on GitHub Actions

### LINKED ISSUE #65: GitHub Action to run Cypress tests

### PR DESCRIPTION
**Pull request by eddiejaoude**
closes #65 

Screenshot 2020-09-19 at 10 28 31

### CODE REVIEW

**Review by BOLT04 — APPROVED** [review]
LGTM, this is awesome @eddiejaoude 👍.
I have been a bit off on this project and it's great to come back and see E2E tests 😃, huge thanks to @Karem1986 as well for starting this great work.

**Comment by eddiejaoude** [comment]
Thanks @BOLT04 👍 

@Karem1986 has really pushed this forwards 💪

**Comment by Karem1986** [comment]
I am so pleased to have carried out Cypress end to end testing with cucumber. Thank you both  for your compliments :)

**Comment by Karem1986** [comment]
David, checked your GitHub profile and i must say i love it! Could you please teach me how to add to mine the "Twitter", LinkedIn" buttons and the stats box?

**Comment by BOLT04** [comment]
@Karem1986 thank you 😄. You can check the GitHub repo and view the raw file, I do that when I see a really cool profile and want to know how they do it 😃, but mine has this in it:

```
<p>
  <a href="https://twitter.com/BOLT2938">
    <img src="https://img.shields.io/twitter/follow/BOLT2938?label=Twitter&logo=twitter&style=for-the-badge" />
  </a>
  <a href="https://www.linkedin.com/in/jos%C3%A9-david-pereira-13ba5315a/">
    <img src="https://img.shields.io/badge/-LinkedIn-blue?style=for-the-badge&logo=linkedin" />
  </a>
</p> 
```

The stats is this:

```
![BOLT04's github stats](https://github-readme-stats.vercel.app/api?username=BOLT04&count_private=true&show_icons=true&theme=tokyonight)
```

You can just change it to your info 👍 and for the stats, you can learn how to customize it [on their repo](https://github.com/anuraghazra/github-readme-stats).

**Pull request merged**
