### PR TITLE
Added some fonts

### PR DESCRIPTION
**Pull request by wbrijesh**
## Added new fonts

The site previously did not have any fonts, it was using arial system font coming from tailwind's stylesheet.

I have added two fonts from google fonts

  - Archivo (for headings)
  - Roboto (For other text)

#### Font Weights

  - Archivo [500, 700]
  - Roboto [400, 500 Italic]
##### Archivo 
500 - Regular Headings
700 - Bold Headings

##### Roboto
400 - Everything Else
500 - Emphasizing on text

### CODE REVIEW

**Review by BOLT04 — COMMENTED** [review]
LGTM 👍, thank you @wbrijesh for adding those fonts. Could you add some screenshots to compare how it looks with these fonts, just to easily see how this PR affects the website?

**Comment by wbrijesh** [comment]
Sure, I'll take screenshots with and without these fonts

**Comment by wbrijesh** [comment]
Before 
Group 1

After Adding Fonts
Group 1(1)

The difference is subtle here but with a bigger headings arial won't look too good

**Comment by wbrijesh** [comment]
**Before**
before

**After**
after

**Comment by wbrijesh** [comment]
arial by itself is good enough for paragraphs but i think it would look better with these fonts

**Review by BOLT04 — APPROVED** [review]
LGTM 👍 , thank you for your contribution @wbrijesh 😃

**Pull request merged**
