### PR TITLE
feat(test): Footer links #81

### LINKED ISSUE #81: HomePage project section could use more testing.
I think the homepage could use more testing. We should make sure project cards have are what we are expecting.

### PR DESCRIPTION
**Pull request by AllanRegush**
closes #81

### CODE REVIEW

**Comment by eddiejaoude** [comment]
@AllanRegush is this still in `draft`?

**Comment by AllanRegush** [comment]
Yes, I have it set for as draft for feedback. Do you want me to split the testing into a few PRs?

**Comment by eddiejaoude** [comment]
Yes I think multiple PRs would be good, a few tests already add value 👍

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
