### PR TITLE
Sample project cards to showcase our projects

### PR DESCRIPTION
**Pull request by ritvij14**
I have made sample cards for showcasing our projects. These have been made with dummy text and an example png, are responsive and enlarge on hover. Didn't make them too complex for now.

For Issue #1 

image

image

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Looks good 👍 , my feedback:

- temporary image is not needed
- can not be merged with example text, suggest using the existing information from our GitHub Organisation  repos

**Comment by ritvij14** [comment]
@eddiejaoude ok I will make the changes about the text, and should I keep the image part empty/remove it for now?

**Comment by eddiejaoude** [comment]
@ritvij14 whatever changes are in the PR, if it is to be merged, it needs to add value to the user/community - I would rather have less "fancy" card but it contained useful information. Put useful in the user's place, if you saw dummy text, that is not useful. 

> should I keep the image part empty/remove it for now

Each project probably has an image, if not, I can create one for you.

**Comment by ritvij14** [comment]
@eddiejaoude I saw images on readme files of EddieBot UI and Eddie Bot map. Others if we want to put, I will need them. 
And yes you are right, proper info is definitely important. For that, I have replaced dummy info with Project descriptions as were there on the repositories, please tell if they look ok. I put a new image in the PR description above.

**Comment by eddiejaoude** [comment]
Looks good 👍 , some of my thoughts

- Don't forget this repo in the list too, add a screenshot of your version of the website when it is done (other projects having their images)
- I will add some screenshots below, for any that do not have any images, use the screenshot below of the GitHub Organisation 

## GitHub Organisation

Screenshot 2020-08-27 at 01 07 17

## EddieBot

Screenshot 2020-08-27 at 01 06 03

## Awesome GitHub Profiles

Screenshot 2020-08-27 at 01 07 30


## Hacktoberfest

Screenshot 2020-08-27 at 01 07 46

**Comment by Arvindjitta** [comment]
> Looks good 👍 , some of my thoughts
> 
> * Don't forget this repo in the list too, add a screenshot of your version of the website when it is done (other projects having their images)
> * I will add some screenshots below, for any that do not have any images, use the screenshot below of the GitHub Organisation
> 
> ## GitHub Organisation
> Screenshot 2020-08-27 at 01 07 17
> 
> ## EddieBot
> Screenshot 2020-08-27 at 01 06 03
> 
> ## Awesome GitHub Profiles
> Screenshot 2020-08-27 at 01 07 30
> 
> ## Hacktoberfest
> Screenshot 2020-08-27 at 01 07 46

brother, what about cards PR i made should i continue it or..?

**Comment by Arvindjitta** [comment]
> Looks good 👍 , my feedback:
> 
> * temporary image is not needed
> * can not be merged with example text, suggest using the existing information from our GitHub Organisation  repos

brother, what about cards PR i made should i continue it or..?

**Comment by eddiejaoude** [comment]
@Arvindjitta I was not sure if you were continuing. My bad, I should have tagged you both to work together. Sorry.

But multiple types of cards will be needed. Because we will have different sections and it would be good for the cards to be different with 2 styles, in this PR it is vertical and in #21 it is horizontal. Other information that will need cards are:

- Projects
- Moderators
- Community members
and more, so it is not wasted 🤓

**Comment by eddiejaoude** [comment]
New images to use for the card, these are square

## GitHub Organisation 

Do not add the binary image to git, use this url `https://user-images.githubusercontent.com/624760/91444606-e687e880-e86c-11ea-9001-522fc212c7c5.png`

Screenshot 2020-08-27 at 13 54 09

## EddieBot

`https://user-images.githubusercontent.com/624760/91444835-3797dc80-e86d-11ea-8dfa-d7993a4d382d.png`

Screenshot 2020-08-27 at 13 56 47

## Website

`https://user-images.githubusercontent.com/624760/91445058-83e31c80-e86d-11ea-8243-3ca11b384d40.png`

Screenshot 2020-08-27 at 13 57 51

## Awesome GitHub profiles

`https://user-images.githubusercontent.com/624760/91445261-cefd2f80-e86d-11ea-8421-4553b29d2e4a.png`

Screenshot 2020-08-27 at 13 59 46

## Support

`https://user-images.githubusercontent.com/624760/91445509-1d123300-e86e-11ea-9648-c5c715355f26.png`

Screenshot 2020-08-27 at 14 03 00


## Hacktoberfest practice

`https://user-images.githubusercontent.com/624760/91445718-61053800-e86e-11ea-81c7-751328c63e85.png`

Screenshot 2020-08-27 at 14 00 20

## EddieBotMap

`https://user-images.githubusercontent.com/624760/91445888-9f9af280-e86e-11ea-8180-9198953bc33d.png`

89235454-1e8d6a00-d5e6-11ea-9c65-8f518b6be785

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Pull request merged**
